<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MUMTEWD00052" name="Command line test 041df8ca-c412-4891-a7ab-e5102b52ce2c" tests="3" failures="1" timestamp="29 Mar 2018 10:02:24 GMT" time="23.8" errors="0">
  <testcase name="navigateToForfotPass" time="4.443" classname="com.HReckAutomation.HReck.forgotPassword"/>
  <testcase name="forgotPasswordMain" time="7.343" classname="com.HReckAutomation.HReck.forgotPassword"/>
  <testcase name="forgotPasswordMain" time="4.339" classname="com.HReckAutomation.HReck.forgotPassword">
    <failure type="java.lang.AssertionError" message="Test case passed expected [New password is generated and email is sent to registered email address.] but found [Problem while sending the mail.]">
      <![CDATA[java.lang.AssertionError: Test case passed expected [New password is generated and email is sent to registered email address.] but found [Problem while sending the mail.]
	at com.HReckAutomation.HReck.forgotPassword.forgotPasswordMain(forgotPassword.java:62)
	at com.mentorstudies.automationframework.TestRunner.main(TestRunner.java:117)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:748)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- forgotPasswordMain -->
</testsuite> <!-- Command line test 041df8ca-c412-4891-a7ab-e5102b52ce2c -->
